"""Additional SEO pages for individualtuition.in — imported by generate-seo-pages.py"""

EXTRA_PAGES = [
    # ── Hubs ──
    {
        "slug": "subjects",
        "title": "Subjects | Individual Tuition Maths, Science & More | CLAPS",
        "description": "Individual tuition by subject — Maths, Physics, Chemistry, Biology, English, Accountancy & all school subjects. One-to-one online KG to +2.",
        "h1": "Individual Tuition by Subject",
        "lede": "Pick the exact subject your child needs — expert one-to-one teachers for every major school subject from primary through Plus Two.",
        "hub_links": [
            ("Maths Individual Tuition", "/maths-individual-tuition/", "Primary to Plus Two"),
            ("Science Individual Tuition", "/science-individual-tuition/", "Integrated & board Science"),
            ("Physics Individual Tuition", "/physics-individual-tuition/", "Class 9 to +2 numericals"),
            ("Chemistry Individual Tuition", "/chemistry-individual-tuition/", "Equations & organic chem"),
            ("Biology Individual Tuition", "/biology-individual-tuition/", "Diagrams, NEET basics"),
            ("English Individual Tuition", "/english-individual-tuition/", "Grammar & literature"),
            ("Accountancy Individual Tuition", "/accountancy-individual-tuition/", "Plus Two Commerce"),
            ("Hindi Individual Tuition", "/hindi-individual-tuition/", "CBSE second language"),
        ],
        "related": [
            ("Classes by grade", "/classes/", "KG to Plus Two"),
            ("CBSE tuition", "/cbse-individual-tuition/", "All subjects"),
            ("Plus Two", "/plus-two-individual-tuition/", "Stream subjects"),
        ],
    },
    {
        "slug": "locations",
        "title": "Individual Tuition Kerala Cities | Online One-to-One | CLAPS",
        "description": "Individual tuition for students in Kochi, Trivandrum, Kozhikode, Thrissur & all Kerala — online one-to-one KG to +2. ClapsLearn.",
        "h1": "Individual Tuition in Kerala — by City",
        "lede": "CLAPS serves families across Kerala with live online individual tuition — no travel needed. Choose your city to see how one-to-one classes work for local syllabuses.",
        "hub_links": [
            ("Individual Tuition Kochi", "/individual-tuition-kochi/", "Ernakulam & nearby"),
            ("Individual Tuition Trivandrum", "/individual-tuition-trivandrum/", "Thiruvananthapuram"),
            ("Individual Tuition Kozhikode", "/individual-tuition-kozhikode/", "Calicut & Malabar"),
            ("Individual Tuition Thrissur", "/individual-tuition-thrissur/", "Central Kerala"),
            ("Individual Tuition Kannur", "/individual-tuition-kannur/", "North Kerala"),
            ("Individual Tuition Kollam", "/individual-tuition-kollam/", "South Kerala"),
        ],
        "related": [
            ("Kerala tuition overview", "/individual-tuition-kerala/", "State-wide"),
            ("Malayalam tuition", "/individual-tuition-malayalam/", "Bilingual classes"),
            ("Online tuition", "/individual-tuition-online/", "How it works"),
        ],
    },
    {
        "slug": "guides",
        "title": "Parent Guides | Choosing Individual Tuition | CLAPS",
        "description": "Guides for parents — what is individual tuition, when your child needs it, how to choose a tutor, online vs home tuition. ClapsLearn.",
        "h1": "Parent Guides to Individual Tuition",
        "lede": "Clear, practical guides to help Kerala and NRI parents understand one-to-one tuition — and decide if CLAPS is right for your child.",
        "hub_links": [
            ("What Is Individual Tuition?", "/what-is-individual-tuition/", "Definition & meaning"),
            ("When Does a Child Need Tuition?", "/when-child-needs-tuition/", "Signs to watch for"),
            ("How to Choose Individual Tuition", "/how-to-choose-individual-tuition/", "Checklist for parents"),
            ("Individual vs Group Tuition", "/individual-tuition-vs-group-tuition/", "Honest comparison"),
            ("Online vs Home Tuition", "/online-tuition-vs-home-tuition/", "Pros & cons"),
            ("Benefits of Individual Tuition", "/benefits-of-individual-tuition/", "Research-backed"),
        ],
        "related": [
            ("Research & evidence", "/research-individual-tuition/", "Studies cited"),
            ("FAQ", "/faq/", "Quick answers"),
            ("How it works", "/how-it-works/", "Join CLAPS"),
        ],
    },
    # ── India & broad intent ──
    {
        "slug": "individual-tuition-india",
        "title": "Individual Tuition India | Best Online One-to-One KG to +2 | CLAPS",
        "description": "Individual tuition across India — online one-to-one classes CBSE, ICSE, state boards. KG to Class 12. 10,000+ students. ClapsLearn.",
        "h1": "Individual Tuition in India",
        "lede": "Quality one-to-one online tuition for Indian students anywhere — CBSE, state boards, ICSE from KG through Plus Two, with flexible timing and subject-expert teachers.",
        "cite": "CLAPS Individual Tuition provides pan-India online one-to-one coaching with syllabus-specialist teachers, serving families in Kerala, metro cities, tier-2 towns, and NRI communities abroad.",
        "sections": [
            ("Online individual tuition for every Indian board", "<p>Whether your child follows CBSE in Delhi, Kerala State syllabus in Kochi, or ICSE in Mumbai, CLAPS matches a dedicated teacher for private live sessions — not a national batch with hundreds of students.</p>"),
            ("Why Indian parents choose online one-to-one", "<ul><li><strong>No commute</strong> — safe, convenient classes from home</li><li><strong>Any city or town</strong> — same quality in rural Kerala or Bangalore</li><li><strong>Board-specific teaching</strong> — SSLC, CBSE, ICSE patterns respected</li><li><strong>Malayalam support</strong> — for Kerala and diaspora families</li><li><strong>Proven scale</strong> — 10,000+ students, 4.9 Google rating</li></ul>"),
            ("Subjects and classes covered", "<p>All major subjects from KG to Plus Two: Maths, Science, Physics, Chemistry, Biology, English, Social Science, Accountancy, and languages. Pick only what you need.</p>"),
        ],
        "related": [
            ("Kerala", "/individual-tuition-kerala/", "Malayalam-friendly"),
            ("CBSE", "/cbse-individual-tuition/", "NCERT aligned"),
            ("NRI abroad", "/nri-individual-tuition/", "Indian syllabus overseas"),
        ],
    },
    # ── Kerala cities ──
    {
        "slug": "individual-tuition-kochi",
        "title": "Individual Tuition Kochi | Online One-to-One Ernakulam | CLAPS",
        "description": "Individual tuition in Kochi & Ernakulam — online one-to-one CBSE, Kerala State & ICSE. KG to +2. Expert teachers. WhatsApp to join CLAPS.",
        "h1": "Individual Tuition in Kochi",
        "lede": "One-to-one online tuition for Kochi and Ernakulam students — CBSE, Kerala State, and ICSE from home, with flexible evening slots after school.",
        "cite": "CLAPS provides online individual tuition to families in Kochi, Ernakulam, Kakkanad, Edapally, and surrounding areas with syllabus-aligned one-to-one classes.",
        "sections": [
            ("Individual tuition for Kochi students", "<p>Kochi families often juggle long commutes and packed schedules. CLAPS online individual tuition removes travel time — your child gets a private teacher on video for exactly the subjects and chapters they need, scheduled after school or on weekends.</p>"),
            ("Popular in Kochi", "<ul><li>CBSE schools in Ernakulam corridor</li><li>Kerala State SSLC & Plus Two preparation</li><li>ICSE Class 10 board focus</li><li>Plus Two Science (PCM/PCB) one-to-one</li><li>Malayalam-medium primary support</li></ul>"),
        ],
        "related": [
            ("All Kerala cities", "/locations/", "Trivandrum, Kozhikode & more"),
            ("Kerala overview", "/individual-tuition-kerala/", "State-wide"),
            ("Class 10", "/class-10-individual-tuition/", "Board year"),
        ],
    },
    {
        "slug": "individual-tuition-trivandrum",
        "title": "Individual Tuition Trivandrum | Thiruvananthapuram Online | CLAPS",
        "description": "Individual tuition in Trivandrum (Thiruvananthapuram) — one-to-one online KG to +2. Kerala State, CBSE & ICSE. ClapsLearn.",
        "h1": "Individual Tuition in Trivandrum",
        "lede": "Private online individual tuition for Thiruvananthapuram students — Kerala State syllabus specialists, CBSE, and Plus Two Science with one teacher per child.",
        "cite": "CLAPS serves Trivandrum and Thiruvananthapuram district families with online one-to-one tuition across Kerala State, CBSE, and ICSE curricula.",
        "sections": [
            ("One-to-one tuition in the capital region", "<p>Trivandrum has strong government and private schools across Kerala State and CBSE boards. CLAPS individual tuition helps when classroom pace is too fast, when board exams approach, or when your child needs focused help in Maths or Science only.</p>"),
            ("What Trivandrum parents book most", "<ul><li>SSLC (Class 10) Kerala State revision</li><li>Plus One & Plus Two Science streams</li><li>CBSE Class 9–10 foundation</li><li>Primary Maths and English</li></ul>"),
        ],
        "related": [
            ("Kerala State syllabus", "/kerala-state-syllabus-tuition/", "SCERT aligned"),
            ("Plus Two", "/plus-two-individual-tuition/", "Higher secondary"),
            ("Locations hub", "/locations/", "Other cities"),
        ],
    },
    {
        "slug": "individual-tuition-kozhikode",
        "title": "Individual Tuition Kozhikode | Calicut Online One-to-One | CLAPS",
        "description": "Individual tuition in Kozhikode (Calicut) — online one-to-one classes Malayalam & English medium. KG to +2. CLAPS ClapsLearn.",
        "h1": "Individual Tuition in Kozhikode",
        "lede": "Malabar-region students in Kozhikode get dedicated online teachers — Kerala State, CBSE, and ICSE individual tuition without leaving home.",
        "cite": "CLAPS Individual Tuition supports Kozhikode (Calicut) families with one-to-one online classes including Malayalam-medium explanation where helpful.",
        "sections": [
            ("Individual tuition for Kozhikode & Malabar", "<p>Kozhikode students often benefit from teachers who explain clearly in Malayalam for Kerala State syllabus while building English exam skills. CLAPS matches teachers to your child's medium and board.</p>"),
            ("Common requests from Kozhikode", "<ul><li>Kerala State primary & high school subjects</li><li>SSLC Maths and Science intensive</li><li>Plus Two PCB & PCM</li><li>English grammar and writing</li></ul>"),
        ],
        "related": [
            ("Malayalam tuition", "/individual-tuition-malayalam/", "Mother-tongue support"),
            ("Kerala overview", "/individual-tuition-kerala/", "All districts"),
            ("Maths tuition", "/maths-individual-tuition/", "All grades"),
        ],
    },
    {
        "slug": "individual-tuition-thrissur",
        "title": "Individual Tuition Thrissur | Online One-to-One Classes | CLAPS",
        "description": "Individual tuition in Thrissur — online one-to-one KG to +2, Kerala State & CBSE. Flexible timing. Part of ClapsLearn.",
        "h1": "Individual Tuition in Thrissur",
        "lede": "Central Kerala students in Thrissur access expert one-to-one online tuition — personalised pacing for SSLC, Plus Two, and primary foundations.",
        "cite": "CLAPS offers online individual tuition to Thrissur district families with subject-specialist teachers for Kerala State and national boards.",
        "sections": [
            ("Why Thrissur families choose CLAPS", "<p>Thrissur combines strong academic culture with busy family schedules. Individual online tuition lets you add focused teaching hours only when needed — one subject, one teacher, your preferred time.</p>"),
        ],
        "related": [
            ("Class 10 SSLC", "/sslc-individual-tuition/", "Board prep"),
            ("Locations", "/locations/", "Kerala cities"),
            ("Online tuition", "/individual-tuition-online/", "Programme overview"),
        ],
    },
    {
        "slug": "individual-tuition-kannur",
        "title": "Individual Tuition Kannur | North Kerala Online Tuition | CLAPS",
        "description": "Individual tuition in Kannur — one-to-one online classes for Kerala State, CBSE & ICSE. KG to +2. ClapsLearn WhatsApp enrolment.",
        "h1": "Individual Tuition in Kannur",
        "lede": "North Kerala students in Kannur get the same expert one-to-one online tuition as metro cities — Kerala State syllabus, CBSE, and board exam preparation.",
        "cite": "CLAPS provides individual online tuition to Kannur and north Kerala families with flexible scheduling and Malayalam-friendly teaching options.",
        "sections": [
            ("Quality tuition without leaving Kannur", "<p>Geography should not limit access to great teachers. CLAPS connects Kannur students with subject experts online for private sessions tailored to SSLC, Plus Two, or primary-level gaps.</p>"),
        ],
        "related": [
            ("Kozhikode", "/individual-tuition-kozhikode/", "Malabar region"),
            ("Kerala State", "/kerala-state-syllabus-tuition/", "SCERT"),
            ("Benefits", "/benefits-of-individual-tuition/", "Why one-to-one"),
        ],
    },
    {
        "slug": "individual-tuition-kollam",
        "title": "Individual Tuition Kollam | South Kerala One-to-One | CLAPS",
        "description": "Individual tuition in Kollam — online one-to-one KG to +2. Kerala State, CBSE. Expert teachers, flexible slots. CLAPS.",
        "h1": "Individual Tuition in Kollam",
        "lede": "South Kerala families in Kollam choose CLAPS for private online individual tuition — especially SSLC, Plus Two, and primary subject support.",
        "cite": "CLAPS Individual Tuition serves Kollam district with one-to-one online classes across school syllabuses and all major subjects.",
        "sections": [
            ("Individual tuition for Kollam students", "<p>From Kollam city to surrounding taluks, online one-to-one tuition brings dedicated teachers to your home screen — ideal for students who need extra attention in Maths, Science, or languages before board exams.</p>"),
        ],
        "related": [
            ("Trivandrum", "/individual-tuition-trivandrum/", "Nearby capital"),
            ("Plus Two", "/plus-two-individual-tuition/", "Class 11–12"),
            ("Kerala overview", "/individual-tuition-kerala/", "State-wide"),
        ],
    },
    # ── Gulf / NRI locations ──
    {
        "slug": "individual-tuition-uae",
        "title": "Individual Tuition UAE | NRI Online CBSE & Kerala | CLAPS",
        "description": "Individual tuition for NRI students in UAE — online one-to-one CBSE, Kerala & ICSE. Indian time-friendly slots. ClapsLearn.",
        "h1": "Individual Tuition in UAE",
        "lede": "Indian curriculum individual tuition for families in Dubai, Abu Dhabi, Sharjah, and across the UAE — live one-to-one classes scheduled around Gulf evenings and weekends.",
        "cite": "CLAPS provides NRI individual tuition to UAE-based Indian students following CBSE, Kerala State, and ICSE syllabuses with timezone-flexible scheduling.",
        "sections": [
            ("Indian syllabus tuition in the Gulf", "<p>UAE schools often follow CBSE or Indian boards with faster pacing than children experienced back home. CLAPS one-to-one tuition fills gaps in Maths, Science, and languages with teachers who know Indian exam patterns.</p>"),
            ("Why UAE parents choose CLAPS", "<ul><li>Evening & weekend slots (Gulf time)</li><li>CBSE & Kerala State experts</li><li>One student, one teacher — no batch</li><li>WhatsApp coordinator support (IST hours)</li></ul>"),
        ],
        "related": [
            ("Dubai", "/individual-tuition-dubai/", "Dubai-specific"),
            ("NRI overview", "/nri-individual-tuition/", "All countries"),
            ("CBSE", "/cbse-individual-tuition/", "Most common board"),
        ],
    },
    {
        "slug": "individual-tuition-dubai",
        "title": "Individual Tuition Dubai | NRI CBSE One-to-One Online | CLAPS",
        "description": "Individual tuition in Dubai for Indian students — online one-to-one CBSE & ICSE KG to +2. ClapsLearn. Enrol via WhatsApp.",
        "h1": "Individual Tuition in Dubai",
        "lede": "Dubai-based Indian families use CLAPS for private online individual tuition — keeping children aligned with CBSE or Kerala syllabus while living abroad.",
        "cite": "CLAPS Individual Tuition supports Dubai NRI students with one-to-one online classes across Indian school boards and flexible Gulf-friendly timings.",
        "sections": [
            ("One-to-one tuition for Dubai NRIs", "<p>Dubai has a large Indian student population in CBSE and ICSE schools. When classroom pace or summer holidays create learning gaps, CLAPS provides a dedicated teacher for targeted subject coaching — from primary Maths to Plus Two Physics.</p>"),
        ],
        "related": [
            ("UAE overview", "/individual-tuition-uae/", "All emirates"),
            ("NRI tuition", "/nri-individual-tuition/", "12+ countries"),
            ("English tuition", "/english-individual-tuition/", "Language support"),
        ],
    },
    # ── More subjects ──
    {
        "slug": "physics-individual-tuition",
        "title": "Physics Individual Tuition Online | Class 9 to +2 | CLAPS",
        "description": "Physics individual tuition — one-to-one numericals, derivations & board prep. CBSE, Kerala, ICSE Class 9–12. ClapsLearn.",
        "h1": "Physics Individual Tuition",
        "lede": "Master Physics with a dedicated teacher — numericals, derivations, diagrams, and exam-style problems explained step-by-step from Class 9 through Plus Two.",
        "cite": "CLAPS offers one-to-one Physics tuition online for secondary and higher secondary students across CBSE, Kerala State, and ICSE syllabuses.",
        "sections": [
            ("Why Physics needs individual attention", "<p>Physics combines concepts, formulas, and problem-solving speed. In a batch, weak chapters get skipped. Individual tuition identifies whether your child struggles with mechanics, electricity, or optics — and fixes that chapter before moving on.</p>"),
            ("Topics covered", "<ul><li>Class 9–10: motion, force, light, electricity basics</li><li>Plus One & Plus Two: full board syllabus + numerical practice</li><li>NEET/JEE foundation (on request)</li></ul>"),
        ],
        "related": [
            ("Chemistry", "/chemistry-individual-tuition/", "Paired Science"),
            ("Maths", "/maths-individual-tuition/", "Numerical skills"),
            ("Plus Two", "/plus-two-individual-tuition/", "PCM stream"),
        ],
    },
    {
        "slug": "chemistry-individual-tuition",
        "title": "Chemistry Individual Tuition | Organic & Inorganic | CLAPS",
        "description": "Chemistry individual tuition online — equations, organic reactions, mole concept one-to-one. Class 9 to +2. ClapsLearn.",
        "h1": "Chemistry Individual Tuition",
        "lede": "Organic reactions, balancing equations, and mole concept — taught one-to-one at your child's pace for CBSE, Kerala State, and ICSE.",
        "cite": "CLAPS provides individual Chemistry tuition with specialist teachers for secondary and Plus Two board preparation.",
        "sections": [
            ("Chemistry one-to-one", "<p>Chemistry rewards repetition and clear explanation of reaction mechanisms. Individual sessions let teachers drill weak areas — whether stoichiometry, periodic table trends, or named organic reactions — until confident.</p>"),
        ],
        "related": [
            ("Physics", "/physics-individual-tuition/", "Science pair"),
            ("Biology", "/biology-individual-tuition/", "PCB stream"),
            ("Class 10", "/class-10-individual-tuition/", "Board Science"),
        ],
    },
    {
        "slug": "biology-individual-tuition",
        "title": "Biology Individual Tuition | Diagrams & NEET Basics | CLAPS",
        "description": "Biology individual tuition — one-to-one diagrams, theory & NEET foundation. Plus One, Plus Two & Class 10. CLAPS online.",
        "h1": "Biology Individual Tuition",
        "lede": "Botany and zoology taught individually — labelled diagrams, NCERT/SCERT theory, and exam answers for Kerala State, CBSE, and ICSE.",
        "cite": "CLAPS Individual Tuition offers one-to-one Biology coaching for board exams and NEET foundation across Indian syllabuses.",
        "sections": [
            ("Biology with personal attention", "<p>Biology has heavy memorisation plus diagram skills. One-to-one tuition helps students who lose marks on unlabelled diagrams or incomplete long answers — common in Kerala and CBSE board papers.</p>"),
        ],
        "related": [
            ("NEET foundation", "/neet-foundation-tuition/", "Medical entrance basics"),
            ("Plus Two PCB", "/plus-two-individual-tuition/", "Stream overview"),
            ("Science tuition", "/science-individual-tuition/", "General Science"),
        ],
    },
    {
        "slug": "accountancy-individual-tuition",
        "title": "Accountancy Individual Tuition | Plus Two Commerce | CLAPS",
        "description": "Accountancy individual tuition online — journals, ledgers, financial statements one-to-one. Plus Two Commerce. ClapsLearn.",
        "h1": "Accountancy Individual Tuition",
        "lede": "Plus Two Accountancy made clear — partnership accounts, company accounts, and GST topics with a dedicated Commerce teacher.",
        "cite": "CLAPS provides one-to-one Accountancy tuition for Kerala Higher Secondary and CBSE Commerce stream students.",
        "sections": [
            ("Commerce subjects, individually taught", "<p>Accountancy errors compound — a missed golden rule in Class 11 affects Class 12 board papers. Individual tuition catches calculation and format mistakes early with repeated problem practice.</p>"),
        ],
        "related": [
            ("Plus Two Commerce", "/plus-two-individual-tuition/", "Full stream"),
            ("Maths tuition", "/maths-individual-tuition/", "Supporting subject"),
            ("Class 10", "/class-10-individual-tuition/", "Before Commerce stream"),
        ],
    },
    {
        "slug": "hindi-individual-tuition",
        "title": "Hindi Individual Tuition Online | CBSE Second Language | CLAPS",
        "description": "Hindi individual tuition — grammar, comprehension & writing one-to-one. CBSE & state boards. KG to Class 10. CLAPS.",
        "h1": "Hindi Individual Tuition",
        "lede": "CBSE and state-board Hindi taught one-to-one — grammar (vyakaran), unseen passages, and essay writing for students who need extra language support.",
        "cite": "CLAPS offers individual Hindi tuition online for second-language requirements across CBSE and selected state syllabuses.",
        "sections": [
            ("Hindi as a second language", "<p>Many Kerala and south Indian CBSE students find Hindi challenging. Individual tuition allows patient, repeated practice of grammar rules and writing formats without classroom embarrassment.</p>"),
        ],
        "related": [
            ("English tuition", "/english-individual-tuition/", "Other language"),
            ("CBSE tuition", "/cbse-individual-tuition/", "Full board"),
            ("Primary tuition", "/primary-individual-tuition/", "Early classes"),
        ],
    },
    # ── More classes ──
    {
        "slug": "class-9-individual-tuition",
        "title": "Class 9 Individual Tuition | Foundation Year Online | CLAPS",
        "description": "Class 9 individual tuition online — Maths, Science & English one-to-one. Build board-year foundation. CBSE & state boards. CLAPS.",
        "h1": "Class 9 Individual Tuition",
        "lede": "Class 9 is the foundation for Class 10 boards — individual tuition catches gaps in Algebra, Science concepts, and languages before the pressure year.",
        "cite": "CLAPS provides Class 9 one-to-one tuition to strengthen fundamentals ahead of SSLC, CBSE, and ICSE board examination years.",
        "sections": [
            ("Why Class 9 matters", "<p>Syllabus jumps in Class 9 — especially Maths and Science. Students who struggle here often face crisis in Class 10. One-to-one tuition in Class 9 is preventive: fix fundamentals early at lower stress.</p>"),
        ],
        "related": [
            ("Class 10", "/class-10-individual-tuition/", "Next year"),
            ("Middle school", "/middle-school-individual-tuition/", "Classes 6–8"),
            ("Maths", "/maths-individual-tuition/", "Algebra focus"),
        ],
    },
    {
        "slug": "plus-one-individual-tuition",
        "title": "Plus One Individual Tuition | Class 11 One-to-One | CLAPS",
        "description": "Plus One (Class 11) individual tuition — Science & Commerce streams one-to-one. Kerala, CBSE, ICSE. ClapsLearn.",
        "h1": "Plus One Individual Tuition",
        "lede": "Class 11 sets the tone for Plus Two boards — individual tuition in PCM, PCB, or Commerce keeps pace with new syllabus depth.",
        "cite": "CLAPS offers Plus One individual tuition for Kerala Higher Secondary, CBSE, and ISC Class 11 students across core stream subjects.",
        "sections": [
            ("Plus One — don't fall behind early", "<p>Plus One introduces calculus, advanced Physics, and Accountancy frameworks that Plus Two exams assume you already know. Individual tuition prevents the common trap of weak Plus One leading to Plus Two struggle.</p>"),
        ],
        "related": [
            ("Plus Two", "/plus-two-individual-tuition/", "Class 12"),
            ("Physics", "/physics-individual-tuition/", "Science stream"),
            ("NEET foundation", "/neet-foundation-tuition/", "Medical path"),
        ],
    },
    {
        "slug": "middle-school-individual-tuition",
        "title": "Middle School Individual Tuition | Classes 6–8 | CLAPS",
        "description": "Middle school individual tuition (Classes 6–8) — Maths, Science & English one-to-one online. All syllabuses. CLAPS.",
        "h1": "Middle School Individual Tuition (Classes 6–8)",
        "lede": "Classes 6 to 8 bridge primary and secondary — individual tuition builds study habits and subject confidence before high-stakes board years.",
        "cite": "CLAPS provides middle-school individual tuition for Classes 6, 7, and 8 across CBSE, Kerala State, and ICSE with subject-specialist teachers.",
        "sections": [
            ("The middle school window", "<p>Research shows tutoring effects are strong in earlier grades. Middle school is ideal for fixing Maths fluency, Science curiosity, and English comprehension before Class 9 syllabus intensity.</p>"),
        ],
        "related": [
            ("Primary", "/primary-individual-tuition/", "Classes 1–5"),
            ("Class 9", "/class-9-individual-tuition/", "Next stage"),
            ("Science", "/science-individual-tuition/", "Integrated Science"),
        ],
    },
    # ── Exam pages ──
    {
        "slug": "sslc-individual-tuition",
        "title": "SSLC Individual Tuition | Kerala Class 10 One-to-One | CLAPS",
        "description": "SSLC individual tuition online — Kerala Class 10 board exam prep one-to-one. Maths, Science, Social & Malayalam. CLAPS.",
        "h1": "SSLC Individual Tuition (Kerala Class 10)",
        "lede": "Kerala SSLC board exam preparation with a private teacher — chapter revision, previous papers, and scoring techniques for Class 10.",
        "cite": "CLAPS Individual Tuition offers SSLC-focused one-to-one online coaching aligned with Kerala State SCERT syllabus and exam patterns.",
        "sections": [
            ("SSLC preparation, one student at a time", "<p>SSLC marks matter for Plus One admissions and stream choice. Individual tuition targets weak papers — whether Maths problems, Science diagrams, or Social Science long answers — with a teacher who tracks your child's mock scores week by week.</p>"),
            ("SSLC subjects", "<ul><li>Mathematics</li><li>Physics, Chemistry, Biology (General Science)</li><li>Social Science</li><li>Malayalam & English</li><li>Hindi / Arabic (as per selection)</li></ul>"),
        ],
        "related": [
            ("Class 10 overview", "/class-10-individual-tuition/", "All boards"),
            ("Kerala State syllabus", "/kerala-state-syllabus-tuition/", "SCERT"),
            ("Maths tuition", "/maths-individual-tuition/", "Problem practice"),
        ],
    },
    {
        "slug": "neet-foundation-tuition",
        "title": "NEET Foundation Tuition | Plus One & Two Biology Focus | CLAPS",
        "description": "NEET foundation individual tuition — one-to-one Biology, Physics & Chemistry basics for medical aspirants. CLAPS online.",
        "h1": "NEET Foundation Individual Tuition",
        "lede": "Build NEET-ready fundamentals in Plus One and Plus Two — individual tuition in PCB with board syllabus priority and entrance-style practice.",
        "cite": "CLAPS provides NEET foundation coaching through one-to-one online sessions for Plus One and Plus Two students alongside board exam preparation.",
        "sections": [
            ("Board first, NEET foundation alongside", "<p>CLAPS focuses on strong board results first — NEET-style MCQ practice and concept depth are added where parents request. Individual tuition lets teachers balance SCERT/CBSE chapter completion with entrance-oriented revision.</p>"),
            ("Typically covered", "<ul><li>Biology: NCERT/SCERT line-by-line clarity</li><li>Chemistry: organic & inorganic basics</li><li>Physics: numerical problem speed</li></ul>"),
        ],
        "related": [
            ("Biology tuition", "/biology-individual-tuition/", "Core NEET subject"),
            ("Plus Two PCB", "/plus-two-individual-tuition/", "Stream"),
            ("Physics", "/physics-individual-tuition/", "Numericals"),
        ],
    },
    # ── Comparison & definition guides ──
    {
        "slug": "individual-tuition-vs-group-tuition",
        "title": "Individual Tuition vs Group Tuition | Which Is Better? | CLAPS",
        "description": "Individual tuition vs group tuition — honest comparison for parents. Attention, cost, pacing & results. Research-backed. CLAPS one-to-one.",
        "h1": "Individual Tuition vs Group Tuition",
        "lede": "Should you choose one-to-one tuition or a batch class? Here is a clear comparison — plus what education research says about each model.",
        "cite": "Individual tuition provides 100% teacher attention per session; group tuition divides one teacher across many students — research favours smaller instructional groups for larger average learning gains.",
        "sections": [
            ("Side-by-side comparison", "<table style=\"width:100%;border-collapse:collapse;font-size:0.9rem;margin-top:0.5rem\"><thead><tr style=\"border-bottom:2px solid var(--line)\"><th style=\"text-align:left;padding:0.5rem 0\">Factor</th><th style=\"padding:0.5rem\">Individual tuition</th><th style=\"padding:0.5rem\">Group tuition</th></tr></thead><tbody><tr style=\"border-bottom:1px solid var(--line)\"><td style=\"padding:0.5rem 0\">Teacher focus</td><td style=\"padding:0.5rem\">100% on your child</td><td style=\"padding:0.5rem\">Shared</td></tr><tr style=\"border-bottom:1px solid var(--line)\"><td style=\"padding:0.5rem 0\">Pace</td><td style=\"padding:0.5rem\">Custom</td><td style=\"padding:0.5rem\">Batch average</td></tr><tr style=\"border-bottom:1px solid var(--line)\"><td style=\"padding:0.5rem 0\">Asking doubts</td><td style=\"padding:0.5rem\">Unlimited</td><td style=\"padding:0.5rem\">Limited time</td></tr><tr style=\"border-bottom:1px solid var(--line)\"><td style=\"padding:0.5rem 0\">Subject choice</td><td style=\"padding:0.5rem\">Any combination</td><td style=\"padding:0.5rem\">Fixed package</td></tr><tr style=\"border-bottom:1px solid var(--line)\"><td style=\"padding:0.5rem 0\">Best for</td><td style=\"padding:0.5rem\">Gaps, boards, shy learners</td><td style=\"padding:0.5rem\">Competitive exam drills</td></tr><tr><td style=\"padding:0.5rem 0\">Research</td><td style=\"padding:0.5rem\">Highest impact tutoring model</td><td style=\"padding:0.5rem\">Varies by batch size</td></tr></tbody></table>"),
            ("When group tuition can work", "<p>Large batches sometimes suit students who only need revision drills or test series. For building understanding from scratch, fixing weak chapters, or preparing a specific child for SSLC/CBSE boards, individual tuition is usually the better fit — which is why CLAPS offers only one-to-one classes.</p>"),
            ("What research says", "<p>The Education Endowment Foundation rates one-to-one tuition as high impact (~5 months extra progress). Meta-analyses find tutoring effects around 0.37 SD (Nickow et al., 2020). Smaller groups help, but individual tuition maximises the personalised elements researchers identify as key. <a href=\"../research-individual-tuition/index.html\">See full research →</a></p>"),
        ],
        "related": [
            ("Benefits", "/benefits-of-individual-tuition/", "10 benefits"),
            ("Online vs home", "/online-tuition-vs-home-tuition/", "Delivery format"),
            ("Online tuition", "/individual-tuition-online/", "CLAPS model"),
        ],
    },
    {
        "slug": "online-tuition-vs-home-tuition",
        "title": "Online Tuition vs Home Tuition | Comparison for Parents | CLAPS",
        "description": "Online tuition vs home tuition (home visit tutor) — safety, quality, flexibility & cost compared. CLAPS online individual tuition.",
        "h1": "Online Tuition vs Home Tuition",
        "lede": "Traditional home tutors visit your house. CLAPS brings the same one-to-one attention online — often with better teacher quality and scheduling flexibility.",
        "cite": "Online individual tuition delivers the same one-to-one instructional model as home visit tutoring with added access to specialist teachers beyond your local area.",
        "sections": [
            ("Online vs tutor at home", "<ul class=\"benefit-list\"><li><strong>Teacher quality</strong> — online connects you to 3,000+ CLAPS experts, not just nearby tutors</li><li><strong>Safety & convenience</strong> — no stranger home visits; learn from your child's desk</li><li><strong>Scheduling</strong> — easier to swap slots or change subjects</li><li><strong>Subject specialists</strong> — separate Physics, Chemistry, Maths teachers</li><li><strong>Consistency</strong> — no tutor cancellations due to travel or rain</li><li><strong>Record-keeping</strong> — coordinators track progress 10 AM – 10 PM</li></ul>"),
            ("When home tuition still appeals", "<p>Some parents prefer in-person for very young KG children. CLAPS online individual tuition works from primary upward with interactive whiteboards — many families find children engage equally well on screen with the right teacher match.</p>"),
        ],
        "related": [
            ("Online tuition", "/individual-tuition-online/", "CLAPS programme"),
            ("How to choose", "/how-to-choose-individual-tuition/", "Parent checklist"),
            ("Kerala cities", "/locations/", "Local families"),
        ],
    },
    {
        "slug": "what-is-individual-tuition",
        "title": "What Is Individual Tuition? | One-to-One Meaning Explained | CLAPS",
        "description": "What is individual tuition? Meaning of one-to-one tuition vs group classes, how it works online, and who it helps. CLAPS guide for parents.",
        "h1": "What Is Individual Tuition?",
        "lede": "Individual tuition means one teacher teaches one student in a private session — also called one-to-one tuition, private tuition, or personal tuition.",
        "cite": "Individual tuition (one-to-one tuition) is a private instructional format where a single educator works with a single learner, allowing fully personalised pacing, feedback, and curriculum focus.",
        "sections": [
            ("Definition", "<p><strong>Individual tuition</strong> is private academic teaching where one qualified teacher works with one student. Unlike school classrooms (1:30 or more) or tuition batches (1:10–40), the entire session focuses on that child's syllabus, gaps, and questions.</p>"),
            ("Other names you might hear", "<ul><li>One-to-one tuition / 1:1 tuition</li><li>Private tuition / personal tuition</li><li>Home tuition (when tutor visits — CLAPS does this online instead)</li><li>Individual coaching / private coaching</li></ul>"),
            ("Individual tuition online", "<p>Online individual tuition uses live video — the teacher and student see and hear each other, share digital whiteboards, and work through problems together. CLAPS has delivered this model to 10,000+ students across India and abroad.</p>"),
            ("Who it helps most", "<p>Students with subject gaps, board exam pressure, learning anxiety in groups, advanced learners bored in batches, and NRI children maintaining Indian syllabuses — all benefit from the individual model. <a href=\"../when-child-needs-tuition/index.html\">When does a child need tuition? →</a></p>"),
        ],
        "related": [
            ("Benefits", "/benefits-of-individual-tuition/", "Why it works"),
            ("vs Group tuition", "/individual-tuition-vs-group-tuition/", "Comparison"),
            ("Join CLAPS", "/how-it-works/", "Get started"),
        ],
    },
    {
        "slug": "when-child-needs-tuition",
        "title": "When Does a Child Need Tuition? | Signs for Parents | CLAPS",
        "description": "When does your child need tuition? 8 signs — falling marks, lost confidence, board year & more. Guide for Kerala & CBSE parents. CLAPS.",
        "h1": "When Does a Child Need Tuition?",
        "lede": "Not every child needs tuition — but these signs suggest one-to-one help could make a real difference before small gaps become big problems.",
        "sections": [
            ("8 signs your child may need individual tuition", "<ul class=\"benefit-list\"><li><strong>Grades dropping</strong> in one or more subjects over consecutive terms</li><li><strong>Avoids homework</strong> or gets frustrated with specific subjects</li><li><strong>Says \"I don't understand\"</strong> but classroom moves on anyway</li><li><strong>Upcoming board year</strong> — Class 10 SSLC/CBSE or Plus Two</li><li><strong>Teacher feedback</strong> mentions attention or participation issues</li><li><strong>Shy in class</strong> — won't ask doubts in front of peers</li><li><strong>School changed</strong> or syllabus jumped (e.g. Class 8 to 9)</li><li><strong>Preparing for stream choice</strong> — needs strong PCM/PCB for Science</li></ul>"),
            ("When tuition may NOT be needed", "<p>If your child is confident, self-studies effectively, and scores consistently well, extra tuition can wait. Individual tuition works best when there is a clear gap, exam deadline, or subject-specific need — not as default pressure on every child.</p>"),
            ("Why individual rather than batch?", "<p>When you decide tuition is needed, individual format fixes the exact gap faster — no waiting for batch schedule to reach your child's weak chapter. <a href=\"../individual-tuition-vs-group-tuition/index.html\">Compare individual vs group →</a></p>"),
        ],
        "related": [
            ("How to choose", "/how-to-choose-individual-tuition/", "Next step"),
            ("Class 10 prep", "/class-10-individual-tuition/", "Board year"),
            ("Research", "/research-individual-tuition/", "Evidence"),
        ],
    },
    {
        "slug": "how-to-choose-individual-tuition",
        "title": "How to Choose Individual Tuition | Parent Checklist | CLAPS",
        "description": "How to choose individual tuition — 10 questions to ask before enrolling. Online tutor quality, syllabus match & safety. CLAPS guide.",
        "h1": "How to Choose Individual Tuition",
        "lede": "Use this checklist before enrolling in any one-to-one tuition — online or home visit — to protect your child's time and your money.",
        "sections": [
            ("10 questions to ask any tuition provider", "<ol><li>Is it truly <strong>one-to-one</strong>, or a small batch marketed as personal?</li><li>Does the teacher know your child's <strong>exact syllabus</strong> (CBSE / Kerala / ICSE)?</li><li>Can you choose <strong>individual subjects</strong> only?</li><li>Can you pick <strong>class timing</strong> that fits school schedule?</li><li>Is the teacher a <strong>subject specialist</strong> or generalist?</li><li>Is there a <strong>coordinator</strong> if issues arise?</li><li>What happens if the teacher is absent — <strong>replacement policy</strong>?</li><li>Can you <strong>pause or change</strong> subjects later?</li><li>Are classes <strong>live</strong> (not only recorded videos)?</li><li>What do other <strong>parents say</strong> — reviews and ratings?</li></ol>"),
            ("How CLAPS answers these", "<ul><li>Every CLAPS class is strictly one teacher, one student</li><li>3,000+ teachers matched by syllabus and subject</li><li>Pick any subjects — Maths only, Science only, etc.</li><li>Flexible slots including evenings & weekends</li><li>Academic coordinators 10 AM – 10 PM on WhatsApp</li><li>4.9/5 Google rating from 1,000+ reviews</li><li>Part of established platform ClapsLearn — 10,000+ students taught</li></ul>"),
        ],
        "related": [
            ("What is individual tuition", "/what-is-individual-tuition/", "Basics"),
            ("Online vs home", "/online-tuition-vs-home-tuition/", "Format choice"),
            ("WhatsApp enrol", "/how-it-works/", "Start with CLAPS"),
        ],
    },
]
